version: 0.1
phases:
  install:
    commands:
      - printenv
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - mkdir -p MyApp
artifacts:
  discard-paths: yes
  files:
    - app.js
    - server.js
